//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherByDay
    {
        public int WeatherID { get; set; }
        public int CityID { get; set; }
        public double TempDay { get; set; }
        public double TempNight { get; set; }
        public string Weather { get; set; }
        public string WeatherIcon { get; set; }
    
        public virtual City City { get; set; }
    }
}
